version: '3'
services:

  command-box-front:
    build: ./docker/front
    container_name: command-box-front
    tty: true
    volumes:
    - ./../command-box-frontend/:/app
    ports:
      - "8080:8080"
    command: >
      ash -c "yarn install &&
        yarn serve"

  command-box-back:
    build: ./docker/back
    container_name: command-box-back
    ports:
      - "8000:8000"
    volumes:
    - ./../command-box-backend:/go/src/github.com/yutaiii/command-box-backend
    working_dir: /go/src/github.com/yutaiii/command-box-backend/
    command: realize start --run

  command-box-db:
    image: mysql:5.7
    container_name: command-box-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: command-box
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
